### ISSUE TITLE
set_project_permission error

### ISSUE THREAD

**Issue by rheinheimer** [UMWRG/HydraPlatform#13]
Minor bug: set_project_permission (HydraServer/lib/sharing.py) does not include "share" when setting the project owner.

Currently:
```
net_i.set_owner(user_i.user_id, read=read, write=write)
```
Should be:
```
net_i.set_owner(user_i.user_id, read=read, write=write, share=share)
```
I assume this was accidental, as set_network_permission is okay and share is otherwise included in the set_project_permission.

I'm working on a fork, which we should eventually merge back into this repo. In the meantime, it's probably quicker to just report here.

**Comment by knoxsp** [comment]
I assume you were referring to proj_i.set_owner(user_i.user_id, read=read, write=write) ? This is the only line i could find that didn't have the share permission. I've fixed this on master

**Comment by rheinheimer** [comment]
Thanks. I think my reference to net_i was a mistake (so, yes, proj_i not net_i), as I was switching back and forth between projects and networks.
