### ISSUE TITLE
get_scenario without data

### ISSUE THREAD

**Issue by rheinheimer** [UMWRG/HydraPlatform#8]
I'm using `get_scenario` to view scenarios, but only need the basic scenario info, not the resourcescenarios that come with it.

So, it would be great to have a flag to omit the resourcescenarios (something like `include_data='N'`, to lighten the load. Related, we should also be able to update the summary without saving back the resourcescenarios.

**Comment by knoxsp** [comment]
This can be done using the 'return_summary' function. Using this flag, resource scenarios and resource group items are not returned.

You should be able to update a scenario's description using update_scenario, with the update_data and update_groups flag set to 'N'. This still requires you to set the name, description, layout etc on the scenario. But means you don't need to include the data or group items.

**Comment by rheinheimer** [comment]
Thanks, exactly what I was looking for.
